FFmpeg installs + testing on multiple versions
DISHDevEx/aEye pull request #14
Opened 2023-06-16 19:14 UTC by JamesF2440

static-ffmpeg now pip installs and is listed in the requirements!
Also added a test, although it is a very simple one
PyTest now runs for python 3.8, 3.8, and 3.10
Section crops, time and frame splits, and now all frame grabs are done via openCV to speed things up.
Tried to package everything up but some of it is still a little weird, may need help on that looking forward.
Committed a test video as well so that anyone cloning the repo won't have to go download a video

2023-06-19 19:49 UTC, vinayakSharm commented on aEye/testVid.mp4
hi james, lets read videos from s3. No videos will go on github.

2023-06-19 19:49 UTC, vinayakSharm commented on aEye/testing.py
> +    video = Video("testVid.mp4") # or any local video, creates Video object
lets read videos from s3 pls

2023-06-19 19:51 UTC, vinayakSharm commented on tests/extract_metadata_test.py
> +    new_vid_obj = Video("aEye/testVid.mp4")
needs to read video from s3.

2023-06-19 19:54 UTC, vinayakSharm commented on aEye/video.py
> +    ##############################################
all code going into main needs to be fully functional. Please move all code that is WIP below into another branch, and keep it for another feature update or next PR

2023-06-19 19:57 UTC, vinayakSharm commented on aEye/video.py
> +    split_on_time(start, end) -> None:
37-64 will go in the processor class. 

Lets integrate these as pipeline processing functionalities. You load a video, you process a video, and then save it back to S3.

2023-06-19 19:57 UTC, vinayakSharm commented on aEye/video.py
> +    extract_metadata -> str:
26-35 will stay in the video class.

2023-06-19 19:58 UTC, JamesF2440 commented on aEye/testVid.mp4
Got it. This'll be the next thing I look into, just wanted to include something for functionality's sake.

2023-06-19 20:01 UTC, vinayakSharm commented on tests/extract_metadata_test.py
> +trash metadata test class featuring a super epic hardcoded video ref
haha pls dont say module is trash :). will be really good once we can get it to read from s3!

2023-06-19 20:01 UTC, vinayakSharm commented on tests/extract_metadata_test.py
> +    assert duration == "10.040000"
good.

2023-06-19 20:07 UTC, vinayakSharm commented on aEye/video.py
> +        os.remove("filter_script.txt")
nice!

Question: do we need to write this script to a txt file or can we run it directly?

2023-06-19 20:07 UTC, vinayakSharm commented on aEye/video.py
> +        print("Encoding ", num_frames, " from ", start_frame)
lets use logging.info

2023-06-19 20:08 UTC, vinayakSharm commented on aEye/video.py
> +        returns da file path as a string
*the

2023-06-19 20:08 UTC, vinayakSharm commented on aEye/video.py
> +        Returns video codec as a string
full sentences pl

2023-06-19 20:25 UTC, vinayakSharm requested changes
Hi james some quick feedback:

(1) Video class is looking solid!
(a) keep the functions mentioned in video class
(b) move the other functions in the processor class that should be in main now

(2) No uploading a movie to github. 22mb is far too large. 

(3) read and write everything to s3 or from s3. Use the load and upload functionality from the processor class. 

(4) Comments need to be pro. so close :). 

(5) remove all code that does not work right now. save it for a later feature update to the code base. 

(6) replace all print statements with logging.

2023-06-20 22:30 UTC, luanlam97 commented on aEye/processor.py
> +                                                  ExpiresIn=100000)
expiration time is too long, makes it shorter pls

2023-06-20 22:30 UTC, luanlam97 commented on aEye/processor.py
> +    def split_on_time(self, start, end):
change function to be english alike
ex: trim_video_from_to( start, end)

2023-06-20 22:30 UTC, luanlam97 commented on aEye/processor.py
> +    def split_on_interval(self, interval):
change this as well
ex: divide_video_by_secs

2023-06-20 22:30 UTC, luanlam97 commented on aEye/processor.py
> +    def crop_video_section(self, section_width, section_height, start_x, start_y):
switch and make the start_x and start_y as the first part of the parameter

2023-06-20 22:30 UTC, luanlam97 commented on aEye/video.py
> +    def get_frames(self):
change to get_num_frames()

2023-06-20 22:30 UTC, luanlam97 commented on aEye/video.py
> +    def getfile(self):
change to get_file

2023-06-26 17:26 UTC, closed without merging