add Aux class and restructure the repo
DISHDevEx/aEye pull request #17
Opened 2023-06-21 23:04 UTC by luanlam97

2023-06-22 15:25 UTC, JamesF2440 commented on .github/workflows/pytest.yml
> +    branches: [main]
I want to run Pytest on every push, not just to main; that way branches with new features can be tested.

2023-06-22 15:25 UTC, JamesF2440 commented on aEye/video.py
> +        (I have a better implementation of this, it will be in the next pr after james adds all of the features.)
Excited to see it!

2023-06-22 15:25 UTC, JamesF2440 commented on aEye/video.py
>      def __repr__(self):
Might want to do a little bit more with this. I feel like repr should return something comprehensive yet easily understandable for humans. For example, rather than just return the video title, return some other useful data like the duration, size, etc?

2023-06-23 22:12 UTC, vinayakSharm commented on README.md
beautiful readme

2023-06-23 22:29 UTC, vinayakSharm commented on aEye/auxiliary.py
> +    def clean_temp(self):
![Screen Shot 2023-06-23 at 4 29 47 PM](https://github.com/DISHDevEx/aEye/assets/60953073/bc479281-6315-4460-b12d-e7f14680ab2b)


doesnt work

2023-06-23 22:30 UTC, vinayakSharm commented on aEye/processor.py
> +    def resize_by_ratio(self,video_list, x_ratio = .8, y_ratio = .8):
docstring the inputs

2023-06-23 22:30 UTC, vinayakSharm commented on aEye/processor.py
> +    def trimmed_from_for(self,video_list, start, duration):
docstring the inputs

2023-06-23 22:30 UTC, vinayakSharm commented on aEye/video.py
> +    def __eq__(self, target):
make the function name more intuitive. no two letter functions

2023-06-23 22:31 UTC, vinayakSharm commented on aEye/video.py
> +    def cleanup(self):
this function broken

2023-06-23 22:32 UTC, vinayakSharm commented on aEye/auxiliary.py
> +                The folder name where the video files belong in the S3 bucket.
prefix is not a param

2023-06-23 22:35 UTC, vinayakSharm commented on aEye/video.py
> +    def cleanup(self):
AttributeError: 'Video' object has no attribute 'cap'

2023-06-23 22:36 UTC, vinayakSharm requested changes
few small comments. 

fix docstrings

fix name for eq function

fix the cleanup function, there is no attribute named cap. 

looks solid.

2023-06-23 22:40 UTC, vinayakSharm commented on aEye/auxiliary.py
> +    def write(self, video_list):
where does this write? can you pls  add a path for local write.

2023-06-23 22:40 UTC, vinayakSharm commented on aEye/auxiliary.py
> +    def write(self, video_list):
if this is local write, can you name this upload_local etc?

2023-06-23 22:43 UTC, vinayakSharm commented on aEye/auxiliary.py
> +                #video.cleanup()
remove unused code

2023-06-23 22:48 UTC, vinayakSharm commented on aEye/auxiliary.py
> +        write() -> None:
is a write_local coming in a future update? will it ever come?

asking, feel free to continue at your discretion

2023-06-23 22:50 UTC, vinayakSharm commented on aEye/auxiliary.py
> +            video_list = [ Video(file=  path + i, title=i) for i in files if (i !='.ipynb_checkpoints' and i != '.gitkeep' ) ]
do a try catch here instead of a specific check for files. 

https://docs.python.org/3/tutorial/errors.html

2023-06-23 22:51 UTC, vinayakSharm commented on aEye/auxiliary.py
> +            video_list = [ Video(file=  path + i, title=i) for i in files if (i !='.ipynb_checkpoints' and i != '.gitkeep' ) ]
https://www.programiz.com/python-programming/exception-handling

2023-06-23 22:52 UTC, vinayakSharm commented on aEye/auxiliary.py
> +                print(command)
logging or print. pick 1 be consistent. 

is it necessary to log the comand, or is there something more reader friendly we can log here?

2023-06-26 16:44 UTC, luanlam97 commented on aEye/processor.py
> +    def trimmed_from_for(self,video_list, start, duration):
resolved

2023-06-26 16:45 UTC, luanlam97 commented on aEye/video.py
> +    def cleanup(self):
removed

2023-06-26 16:45 UTC, luanlam97 commented on aEye/auxiliary.py
> +                The folder name where the video files belong in the S3 bucket.
removed

2023-06-26 16:45 UTC, luanlam97 commented on aEye/auxiliary.py
> +    def write(self, video_list):
resolved

2023-06-26 16:45 UTC, luanlam97 commented on aEye/auxiliary.py
> +                #video.cleanup()
removed

2023-06-26 16:46 UTC, luanlam97 commented on aEye/auxiliary.py
> +        write() -> None:
resolved

2023-06-26 16:48 UTC, luanlam97 commented on aEye/auxiliary.py
> +                print(command)
It will be logging now 
(I was using print to debug labels)

2023-06-26 17:09 UTC, vinayakSharm commented on aEye/processor.py
> +    def add_label_trimming_from_for(self,video_list, start, duration):
this function doesnt need "from_for". 

trimming implies that there will be variables involved for start, end etc. 

add_label_trimming should suffice.

2023-06-26 17:17 UTC, vinayakSharm commented on aEye/auxiliary.py
> +    def execute_label_and_write_to(self, video_list, location = None):
execute_label_and_write_local. 

can think about more interesting logic, but this is great for a v0

2023-06-26 17:18 UTC, vinayakSharm commented on aEye/auxiliary.py
> +    def execute_label_and_write_to(self, video_list, location = None):
using location variable here, but path variable in other places. for consistency pick one variable name and use it everywhere

2023-06-26 17:19 UTC, vinayakSharm commented on aEye/auxiliary.py
> +    def clean_temp(self):
if I pass a location to def execute_label_and_write_to(self, video_list, location = None). 

then when I call the clean function is does not clean the videos. pls resolve this bug :)

2023-06-26 17:23 UTC, vinayakSharm commented on aEye/processor.py
> +        resize_by_ratio(x_ratio, y_ratio,target) -> None:
update docstrings as per the new function names

2023-06-26 17:24 UTC, vinayakSharm commented on aEye/processor.py
> +                The list of video that contains the resize modification.
contains labels :)

2023-06-26 17:24 UTC, vinayakSharm commented on aEye/processor.py
> +        #go to each video and add the resizing ffmpeg modification
period. capitalize the sentence

2023-06-26 17:25 UTC, vinayakSharm commented on aEye/processor.py
> +        This method will add the trim modification with desired parameters to the video list.
add the word label

2023-06-26 17:31 UTC, luanlam97 commented on aEye/processor.py
> +    def add_label_trimming_from_for(self,video_list, start, duration):
I will pick (3)

2023-06-26 17:32 UTC, luanlam97 commented on aEye/auxiliary.py
> +    def execute_label_and_write_to(self, video_list, location = None):
I will use path for all for consistency

2023-06-26 18:11 UTC, luanlam97 commented on aEye/processor.py
> +        This method will add the trim modification with desired parameters to the video list.
I edited all modification to the word label.

2023-06-26 18:11 UTC, luanlam97 commented on aEye/processor.py
> +        #go to each video and add the resizing ffmpeg modification
resolved

2023-06-26 18:11 UTC, luanlam97 commented on aEye/processor.py
> +        resize_by_ratio(x_ratio, y_ratio,target) -> None:
fixed

2023-06-26 20:59 UTC, vinayakSharm approved these changes

2023-06-26 21:55 UTC, merged