Luan
DISHDevEx/aEye pull request #9
Opened 2023-06-12 21:10 UTC by luanlam97

fixes loader and process module, and video class
adds comments and docstring

2023-06-12 22:54 UTC, vinayakSharm requested changes
Hi Luan, 

Pls add print statements everytime you run something. You can also do logging. Start, process happening, any s3 paths, completion logged (duration is fine). 


Make a class with some naming similar to process_video.

Process_video should have the following: load, resize, load_and_resize functions. 

Class video can be maintained. Move the resize function out of video and into the processor class. The write video can stay. Can you think of any other functions the video class should have? (maybe change codec, not sure...

2023-06-19 15:53 UTC, vinayakSharm requested changes
Hi Luan , pls see the code comments below. 

Some feedback for all of the code: pls use updated documentation standards as seen in fonpr. 

This means module docstrings, more attribute information etc. 

ex file with great docs https://github.com/DISHDevEx/fonpr/blob/main/fonpr/tf_infrastructure/driver.py

2023-06-19 15:53 UTC, vinayakSharm commented on aEye/processor.py
> +            if i["Key"] == prefix:
really clean way to skip over prefix

2023-06-19 15:53 UTC, vinayakSharm commented on aEye/processor.py
> +            if i["Key"] == prefix:
add a comment here explaining why you are put this if statement. Will help future readers and maintainers

2023-06-19 15:53 UTC, vinayakSharm commented on aEye/processor.py
> +            out.release()
good

2023-06-19 15:53 UTC, vinayakSharm commented on README.md
> +P = Processor()
name this variable a full english word, and lower case

![Screen Shot 2023-06-19 at 9 42 05 AM](https://github.com/DISHDevEx/aEye/assets/60953073/3926e178-7115-4b2d-9310-3a963362f702)

2023-06-19 15:53 UTC, vinayakSharm commented on aEye/processor.py
> +        print(f"successfully resized all video by ratio of {x_ratio} and {y_ratio}" )
dont need both logging and print statements. just use logging. should be ok

2023-06-19 15:53 UTC, vinayakSharm commented on aEye/processor.py
> +        print("successfully upload the output files and remove them from local machine")
pls print the s3 path where the videos are uploaded to.

2023-06-19 15:53 UTC, vinayakSharm commented on aEye/processor.py
> +            path = 'data/out_put_' + video.title
dont upload to a folder named data. 

upload to a different folder. something more intuitive, such as resized videos or modified videos etc. 

for custom upload folder compatability you may want to pass in a variable to this function indicating what operation took place on the video

2023-06-19 16:56 UTC, luanlam97 commented on README.md
> +P = Processor()
I changed P variable into process variable in readme.
Not the best but it is understandable enough.

2023-06-19 16:56 UTC, luanlam97 commented on aEye/processor.py
> +        self.pipeline = ['ffmpeg']
I removed this variable from this pr.
I accidentally included this from my next pr.

2023-06-19 16:56 UTC, luanlam97 commented on aEye/processor.py
> +            url = s3.generate_presigned_url( ClientMethod='get_object', Params={ 'Bucket': bucket, 'Key': i["Key"] } ,ExpiresIn=5)
In the next pr, I will change this and make it into a method in Video class in case we need to this url many time.
Also in the next pr, this method will be called only when we execute the modification so we can have expiration time parameter really small for security purposes.

2023-06-19 16:56 UTC, luanlam97 commented on aEye/processor.py
> +    def load(self, bucket=  'aeye-data-bucket', prefix='input_video/'):
This function will return the list of videos now

2023-06-19 16:57 UTC, luanlam97 commented on requirements.txt
> +boto3>=1.26.29
removed it

2023-06-19 16:57 UTC, luanlam97 commented on aEye/processor.py
> +            if i["Key"] == prefix:
i added comments to explain to the skip

2023-06-19 17:00 UTC, luanlam97 commented on aEye/processor.py
> +        print("successfully upload the output files and remove them from local machine")
I added the print statement that shows which s3 path the videos were uploaded to

2023-06-19 17:00 UTC, luanlam97 commented on aEye/processor.py
> +            path = 'data/out_put_' + video.title
I changed the data/ folder into modified/ folder.
I will add the custom upload folder name functionality in the next pr

2023-06-19 17:06 UTC, vinayakSharm commented on aEye/processor.py
> +            if i["Key"] == prefix:
Full sentences Luan with periods.  :)

2023-06-19 17:07 UTC, vinayakSharm commented on aEye/processor.py
> +        both has to be non negative and non zero value
Full sentences with periods pls and thank u

2023-06-19 17:07 UTC, vinayakSharm commented on README.md
> +P = Processor()
works!

2023-06-19 17:08 UTC, vinayakSharm commented on aEye/video.py
>  class Video:
need docstrings for this file

2023-06-19 17:09 UTC, vinayakSharm commented on aEye/processor.py
> +    def load_and_resize(self, bucket=  'aeye-data-bucket', prefix='input_video/', x_ratio = .8, y_ratio = .8):
docstrings

2023-06-19 17:12 UTC, vinayakSharm requested changes
docstrings are all thats needed for this pr at this moment. 

(1)all comments should be full sentences if standalone. Capitalize first word end with period. thx

(2) All files should have a comment block at the top describing what this file does. 

(3) Classes should start with brief description, list all attributes, and all methods. Explaining the types and functionality:    
ex/
 """
    Driver interacts with the NAPP environment using a tf agent policy.
    The drivers main responsibilities are to catalogue action, current state, next state, reward.
    Driver has all the functions needed to make changes in napp as suggested by agent, and to calculate the observations, rewards.

    Attributes
    ----------
        prom_endpoint: str
            "ip:port" for the prometheus server endpoint.

        wait_period = int
            The time interval driver should wait for in seconds to retrive the observations after taking an action.

    Methods
    -------
        reward_function(throughput, infra_cost) -> float:
            Calculates and returns the reward(maximizing profit).
            Uses throughput and infra_cost to calculate reward.

        get_observations() -> List[float]:
            Queries the prometheus server (ip:port) to receive observations.

        get_infra_cost(size) -> float:
            Uses ec2_cost_calculator to get the hourly pricing of the EC2 sizes specified (as a list).

        update_yml(size,gh_url,dir_name)-> None:
            Updates the yml file to modify NAPP upf sizing.

        take_action_get_next_timestep(action_step):
            Takes an action, waits some time, and finds the next state + reward pair.

        drive(max_steps, policy, observer):
            Uses the tf agents policy specified to interact with environment. The interactions,
            or experience, is the placed inside the observer (typically replay buffer for DQN).

    """
    
    (4)All functions should have a brief description, and describe inputs and returns. If no input then omit. if no return then omit. 
ex/
        """
        Calculates the average rx and tx for eth0 and ogstun interfaces summed across all pod_idxs. Also calculates the hourly cost for all nodes running UPF's.

        Returns
        -------
            observations: List
                [Rx_eth0,Rx_ogstun,Tx_eth0,Tx_ogstun,cost]
        """

2023-06-19 20:24 UTC, vinayakSharm approved these changes
looks good. 

fix pytest and pylint as part of next features.

2023-06-19 20:25 UTC, luanlam97 commented
thank you!!!

2023-06-19 20:25 UTC, merged